name: My Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set environment variables
        run: |
          echo "API_KEY_HERE=${{ secrets.API_KEY_HERE }}" >> $GITHUB_ENV
        env:
          API_KEY_HERE: ${{ secrets.API_KEY_HERE }}
