name: Secure Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Use Secret in Workflow
      run: echo "The API key is ${{ secrets.API_KEY_HERE }}"
      # Here, you can use the secret in your commands or scripts

    - name: Use Secret in Application
      run: ./weather_app --API_KEY_HERE="${{ secrets.API_KEY_HERE }}"
