name: My Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set environment variables
        run: |
          echo "MY_SECRET_KEY=${{ secrets.MY_SECRET_KEY }}" >> $GITHUB_ENV

      - name: Run your script
        run: script.js
        env:
          MY_SECRET_KEY: ${{ secrets.MY_SECRET_KEY }}
